# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish NPM package

run-name: Publish ${{ github.event.release.name }}

on:
  release:
    types:
      - published
  workflow_call:
    inputs:
      skipTest:
        description: 'Skip test job (only if done before)'
        type: boolean
        default: false
        required: false
      ref:
        description: 'Git ref to publish'
        type: string
        required: false
    secrets:
      NPM_TOKEN:
        description: 'NPM access token for publishing to npm registry'
        required: true

jobs:
  test:
    name: Testing package
    if: ${{ !inputs.skipTest }}
    uses: ./.github/workflows/node.js.yml

  publish:
    name: Publish to NPM registry
    needs: test
    if: ${{ !failure() }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
      - name: Preparing package check
        run: npm ci
      - name: Auditing package
        run: npm audit
      - name: Check outdated dependencies
        run: npm outdated
      - name: Publishing package
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
