# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish NPM package

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      skipTest:
        description: 'Skip test job (only if done before)'
        type: boolean
        default: false
        required: false

jobs:
  test:
    name: Testing package
    if: ${{ !inputs.skipTest }}
    uses: ./.github/workflows/node.js.yml

  publish:
    name: Publish to NPM registry
    needs: test
    if: ${{ !failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
