name: Push new version to main branch

on:
  push:
    tags:
      - 'v*'
  workflow_call:
    inputs:
      ref:
        description: 'Ref to push to main branch'
        type: string
        required: false

jobs:
  pr:
    name: Pull request to main branch
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
          fetch-depth: 0
      - run: gh pr create --fill-verbose
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge:
    name: Merge to main branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-tags: true
      - run: git merge $REF
        env:
          REF: ${{ inputs.ref || format('origin/{0}', github.ref_name) }}
      - run: git push
